version: '3'

services:
    web-node-js:
        image: chakorn/nodejs:latest
        container_name: nodejs
        ports:
            - "3000:3000"
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
    mongodb:
        image: mongo:latest
        container_name: mongoDB
        ports: 
            - "27017:27017"
        
